# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitlabctl < Formula
  desc ""
  homepage ""
  version "0.1.14"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/PennState/gitlabctl/releases/download/v0.1.14/gitlabctl_0.1.14_darwin_amd64.tar.gz"
      sha256 "58791673f73fc87600a2098e4cec31777a0fae0e165cb6b7e4fad1a4f264039b"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/PennState/gitlabctl/releases/download/v0.1.14/gitlabctl_0.1.14_linux_amd64.tar.gz"
      sha256 "99e11bf7674d97b7f765b9f85f615c981e26b41ec2b15b27bab9f37fcfde9f47"
    end
  end

  def install
    bin.install "gitlabctl"
  end
end
