# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sso2aws < Formula
  desc ""
  homepage ""
  version "0.1.3"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/PennState/sso2aws/releases/download/v0.1.3/sso2aws_0.1.3_darwin_amd64.tar.gz"
      sha256 "0a8dd29beace8aeac21fa77dee3874e112619224f8c8a7e79dc089b5a261ad43"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/PennState/sso2aws/releases/download/v0.1.3/sso2aws_0.1.3_linux_amd64.tar.gz"
      sha256 "3a9628e811a353f59e536967f0c930d25e0406fa40751f722e094ffa0aafac65"
    end
  end

  def install
    bin.install "sso2aws"
  end
end
