# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sso2aws < Formula
  desc ""
  homepage ""
  version "0.1.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/PennState/sso2aws/releases/download/v0.1.4/sso2aws_0.1.4_darwin_amd64.tar.gz"
      sha256 "5bd63507757d9aa0287ba2e668c458425439b310430aec46a1199e4fce309db9"

      def install
        bin.install "sso2aws"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/PennState/sso2aws/releases/download/v0.1.4/sso2aws_0.1.4_linux_amd64.tar.gz"
      sha256 "6e6e59481d129d3693607ef2a60b3a4d04bb04ed0a5acea3b81d5607508f0986"

      def install
        bin.install "sso2aws"
      end
    end
  end
end
